### ISSUE TITLE
Adding more than one Source causes no Zones to show

### ISSUE THREAD

**Issue by scotttherobot** [jslove/xap_controller#1]
First of all, this component is great. It'd be awesome to see it merged into HA.

I'm struggling a bit to get this working right. I am running HomeAssistant `0.49.0` and I have two XAP800s, though I'm currently testing with only one of them connected configured with unit code 0.

When I initially tried to set up in Stereo-pair, single-unit mode, an exception would be thrown due to the XAP responding with "ERROR - Argument error" (something I think had to do with the unit code?). After playing with the different syntax options and getting more comfy with the `XAPX00` module, I was able to get something working with the following entry in my HomeAssistant configuration file:

```
media_player:
  - platform: xap_controller
    path: /dev/ttyUSB0
    name: Xap
    scan_interval: 30
    stereo: 0
    baud: 38400
    zones:
      'Office':
        - "0:1"
        - "0:2"
      'Guest Room':
        - "0:3"
        - "0:4"
    sources:
      'Sonos':
        - "0:1"
        - "0:2"
```

This will successfully show two zones and one source in HomeAssistant. The issue I'm having now is that as soon as I add more than one `source`, my `zones` disappear from the HomeAssistant UI and only the first `source` shows. For example, modifying the `sources:` section to this:

```
    sources:
      'Sonos':
        - "0:1"
        - "0:2"
      'Chromecast':
        - "0:11"
        - "0:12"
```

results in all the `zones` disappearing from the UI and only the `Sonos` source showing (or whatever source is defined first).

I do not see any logs in the HomeAssistant output relating to this component. I have tried to enable debug logging in the `XAPX00` module however since HA reinitializes the dependencies on each boot, it wipes out my changes.

Is there anything that I am obviously doing wrong? Any other debugging steps that I should take?
