### ISSUE TITLE
XAP Not Connected On Serial Port

### ISSUE THREAD

**Issue by rjDipcord** [jslove/xap_controller#12]
Is this an issue in my configuration? A hardware problem?

I have been struggling with this problem for hours. Just trying to get HA to communicate with my XAP800.

This error originated from a custom integration.

```
Logger: custom_components.xap_controller.media_player
Source: custom_components/xap_controller/media_player.py:207
Integration: xap_controller (documentation)
First occurred: February 11, 2024 at 7:08:02 PM (1 occurrences)
Last logged: February 11, 2024 at 7:08:02 PM

Not connected to /dev/ttyUSB0
```
No matter what path I use to access my serial adapter, xap_controller seems to refuse to connect. 

```
This error originated from a custom integration.

Logger: custom_components.xap_controller.media_player
Source: custom_components/xap_controller/media_player.py:207
Integration: xap_controller (documentation)
First occurred: February 11, 2024 at 7:26:43 PM (1 occurrences)
Last logged: February 11, 2024 at 7:26:43 PM

Not connected to /dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTDMJW95-if00-port0
```

My baud rate is correct. The serial adapter works, because I can access the XAP800 in Gware, but home assistant can't seem to connect at all!

Here is my configuration.yaml:

```
#XAP CONFIG
media_player:
   - platform: xap_controller
     path: /dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTDMJW95-if00-port0
     stereo: 0 # 1 or 0, default is 0, recommend explicitly listing sterero channels
     baud: 38400 #default
     XAPType: XAP800 # XAP800 or XAP400, default is XAP800
     zones:
       'Office':
         - 1
     sources:
       'Home Audio':
         - 1
```
Any assistance tremendously appreciated!
